name: "π™‹ Meeting"
description: 'ν€μ›λ“¤κ³Ό λ…Όμν•  λ‚΄μ©μ΄ μλ‚μ”?'
labels: "π™‹ Meeting"
body:
  - type: textarea
    attributes:
      label: π’¬ Description
      description: νμ μ£Όμ μ— λ€ν• μ„¤λ…μ„ μ‘μ„±ν•΄μ£Όμ„Έμ”!
      placeholder: μμ„Έν μ μ„μλ΅ μΆ‹μµλ‹λ‹¤!
    validations:
      required: true