#!/usr/bin/env sh

# 스테이징된 /back 하위 .kt 파일만 추출, 반환된 파일이 없으면 정상 종료
stagedKtFiles=$(git diff --staged --name-only | grep '^back/.*\.kt$' || true)

if [ -n "$stagedKtFiles" ]; then
  echo "==================== ktlintFormat::start ========================"
  echo "🔎 Running ktlintFormat"
  cd back && ./gradlew ktlintFormat && cd ..
  echo "$stagedKtFiles" | xargs git add
  echo "✅ Ktlint format completed."
  echo "==================== ktlintFormat::end ========================"
fi
